new Text: LunaIcon[9];


stock LoadGlobalTextDraw()
{
    LunaIcon[0] = TextDrawCreate(303.000, 2.000, "/");
    TextDrawLetterSize(LunaIcon[0], 0.650, 1.399);
    TextDrawAlignment(LunaIcon[0], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(LunaIcon[0], 1520156671);
    TextDrawSetShadow(LunaIcon[0], 0);
    TextDrawSetOutline(LunaIcon[0], 0);
    TextDrawBackgroundColour(LunaIcon[0], 150);
    TextDrawFont(LunaIcon[0], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(LunaIcon[0], true);

    LunaIcon[1] = TextDrawCreate(303.000, 2.000, "/");
    TextDrawLetterSize(LunaIcon[1], 0.650, 1.399);
    TextDrawAlignment(LunaIcon[1], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(LunaIcon[1], 1520156671);
    TextDrawSetShadow(LunaIcon[1], 0);
    TextDrawSetOutline(LunaIcon[1], 0);
    TextDrawBackgroundColour(LunaIcon[1], 150);
    TextDrawFont(LunaIcon[1], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(LunaIcon[1], true);

    LunaIcon[2] = TextDrawCreate(303.000, 2.000, "/");
    TextDrawLetterSize(LunaIcon[2], 0.650, 1.399);
    TextDrawAlignment(LunaIcon[2], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(LunaIcon[2], 1520156671);
    TextDrawSetShadow(LunaIcon[2], 0);
    TextDrawSetOutline(LunaIcon[2], 0);
    TextDrawBackgroundColour(LunaIcon[2], 150);
    TextDrawFont(LunaIcon[2], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(LunaIcon[2], true);

    LunaIcon[3] = TextDrawCreate(303.000, 2.000, "/");
    TextDrawLetterSize(LunaIcon[3], 0.650, 1.399);
    TextDrawAlignment(LunaIcon[3], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(LunaIcon[3], 1520156671);
    TextDrawSetShadow(LunaIcon[3], 0);
    TextDrawSetOutline(LunaIcon[3], 0);
    TextDrawBackgroundColour(LunaIcon[3], 150);
    TextDrawFont(LunaIcon[3], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(LunaIcon[3], true);

    LunaIcon[4] = TextDrawCreate(303.000, 2.000, "/");
    TextDrawLetterSize(LunaIcon[4], 0.650, 1.399);
    TextDrawAlignment(LunaIcon[4], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(LunaIcon[4], 1520156671);
    TextDrawSetShadow(LunaIcon[4], 0);
    TextDrawSetOutline(LunaIcon[4], 0);
    TextDrawBackgroundColour(LunaIcon[4], 150);
    TextDrawFont(LunaIcon[4], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(LunaIcon[4], true);

    LunaIcon[5] = TextDrawCreate(297.000, 4.000, "LD_BEAT:chit");
    TextDrawTextSize(LunaIcon[5], 7.000, 8.000);
    TextDrawAlignment(LunaIcon[5], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(LunaIcon[5], 1520156671);
    TextDrawSetShadow(LunaIcon[5], 0);
    TextDrawSetOutline(LunaIcon[5], 0);
    TextDrawBackgroundColour(LunaIcon[5], 255);
    TextDrawFont(LunaIcon[5], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(LunaIcon[5], true);

    LunaIcon[6] = TextDrawCreate(315.000, 3.000, "una");
    TextDrawLetterSize(LunaIcon[6], 0.290, 1.399);
    TextDrawAlignment(LunaIcon[6], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(LunaIcon[6], -1);
    TextDrawSetShadow(LunaIcon[6], 0);
    TextDrawSetOutline(LunaIcon[6], 0);
    TextDrawBackgroundColour(LunaIcon[6], 150);
    TextDrawFont(LunaIcon[6], TEXT_DRAW_FONT_1);
    TextDrawSetProportional(LunaIcon[6], true);

    LunaIcon[7] = TextDrawCreate(305.000, 12.000, "LD_SPAC:white");
    TextDrawTextSize(LunaIcon[7], 9.000, 3.000);
    TextDrawAlignment(LunaIcon[7], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(LunaIcon[7], 1520156671);
    TextDrawSetShadow(LunaIcon[7], 0);
    TextDrawSetOutline(LunaIcon[7], 0);
    TextDrawBackgroundColour(LunaIcon[7], 255);
    TextDrawFont(LunaIcon[7], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(LunaIcon[7], true);

    LunaIcon[8] = TextDrawCreate(297.000, 20.000, "PARTICLE:lamp_shad_64");
    TextDrawTextSize(LunaIcon[8], 41.000, -4.000);
    TextDrawAlignment(LunaIcon[8], TEXT_DRAW_ALIGN_LEFT);
    TextDrawColour(LunaIcon[8], 1520156671);
    TextDrawSetShadow(LunaIcon[8], 0);
    TextDrawSetOutline(LunaIcon[8], 0);
    TextDrawBackgroundColour(LunaIcon[8], 255);
    TextDrawFont(LunaIcon[8], TEXT_DRAW_FONT_SPRITE_DRAW);
    TextDrawSetProportional(LunaIcon[8], true);

    return 1;
}

// stock LoadPlayerTextDraw(playerid) return 1;