// thanks: https://www.schemecolor.com/

#define LUNA_COL				0x5A9BBFAA
#define LUNA_WHITE				0xFFFFFFAA
#define LUNA_GOLD				0xEAC335AA
#define LUNA_LIGHT_BLUE			0x9BD7FBAA
#define LUNA_BURNT				0x987554AA
#define LUNA_DUSTY_PEACH		0xDFBB8BAA
#define LUNA_RED_SUN			0xF85C4DAA
#define LUNA_GRAY				0x949494AA
#define LUNA_GREEN				0x97CB7FAA

#define E_LUNA_COL				"{5A9BBF}"
#define E_LUNA_WHITE			"{FFFFFF}"
#define E_LUNA_GOLD				"{EAC335}"
#define E_LUNA_LIGHT_BLUE		"{9BD7FB}"
#define E_LUNA_BURNT			"{987554}"
#define E_LUNA_DUSTY_PEACH		"{DFBB8B}"
#define E_LUNA_RED_SUN			"{F85C4D}"
#define E_LUNA_GRAY				"{949494}"
#define E_LUNA_GREEN			"{97CB7F}"
